import type { CharacterDefinition, ObstacleDefinition, StageReached } from '../types/app';

export const gameConfig = {
  logicalWidth: 390,
  logicalHeight: 844,
  groundY: 708,
  runnerStartX: 84,
  scoreRatePerSecond: 10,
  backgroundColor: '#030A03',
  hudPadding: 24,
};

export const stageThresholds: Array<{ stage: StageReached; minScore: number }> = [
  { stage: 'Discovery', minScore: 0 },
  { stage: 'Design', minScore: 180 },
  { stage: 'Build', minScore: 420 },
  { stage: 'UAT', minScore: 760 },
  { stage: 'Go Live', minScore: 1080 },
];

export const characters: CharacterDefinition[] = [
  // Platinum sponsors
  { key: 'runner-deloitte',  label: 'Deloitte Digital',   logoMark: 'D',    tier: 'Platinum',       palette: { body: 0x1a1a1a, accent: 0x86BC25, arms: 0xffffff } },
  { key: 'runner-spire',     label: 'spire.',             logoMark: 'sp',   tier: 'Platinum',       palette: { body: 0x1a1a1a, accent: 0x00AEEF, arms: 0xffffff } },
  { key: 'runner-delaware',  label: 'delaware',           logoMark: 'de',   tier: 'Platinum',       palette: { body: 0xffffff, accent: 0xC8102E, arms: 0xffffff } },
  // Groundbreakers partners
  { key: 'runner-accenture', label: 'Accenture',          logoMark: 'A>',   tier: 'Groundbreakers', palette: { body: 0x1a1a1a, accent: 0xA100FF, arms: 0xffffff } },
  { key: 'runner-pwc',       label: 'PwC',                logoMark: 'PwC',  tier: 'Groundbreakers', palette: { body: 0xffffff, accent: 0xE0301E, arms: 0xffffff } },
  { key: 'runner-capgemini', label: 'Capgemini',          logoMark: 'cg',   tier: 'Groundbreakers', palette: { body: 0xffffff, accent: 0x0070AD, arms: 0xffffff } },
  { key: 'runner-valantic',  label: 'valantic',           logoMark: 'va',   tier: 'Groundbreakers', palette: { body: 0xffffff, accent: 0x00A4B4, arms: 0xffffff } },
  { key: 'runner-easi',      label: 'easi',               logoMark: 'ea',   tier: 'Groundbreakers', palette: { body: 0xffffff, accent: 0x1B2A6B, arms: 0xffffff } },
  { key: 'runner-inetum',    label: 'inetum',             logoMark: 'in',   tier: 'Groundbreakers', palette: { body: 0xffffff, accent: 0x005CA9, arms: 0xffffff } },
  // Navigators partners
  { key: 'runner-genesys',   label: 'Genesys',            logoMark: 'G',    tier: 'Navigators',     palette: { body: 0xffffff, accent: 0xFF4F1F, arms: 0xffffff } },
  { key: 'runner-butler',    label: 'Butler',             logoMark: 'B',    tier: 'Navigators',     palette: { body: 0xfff3e0, accent: 0xC87941, arms: 0xfff3e0 } },
  { key: 'runner-novera',    label: 'Novera Solutions',   logoMark: 'N',    tier: 'Navigators',     palette: { body: 0xffffff, accent: 0x6B8E5E, arms: 0xffffff } },
  { key: 'runner-nrb',       label: 'NRB',                logoMark: 'NRB',  tier: 'Navigators',     palette: { body: 0x1B3A6B, accent: 0xffffff, arms: 0xaabbcc } },
];

export const obstacleDefinitions: ObstacleDefinition[] = [
  {
    key: 'scope-creep',
    label: 'Scope Creep',
    assetKey: 'obstacle-scope-creep',
    accent: 0x3d7fab,
    cropX: 269,
    cropY: 119,
    cropWidth: 507,
    cropHeight: 823,
    weight: 1.2,
    width: 94,
    height: 232,
    bodyWidth: 54,
    bodyHeight: 198,
    bodyOffsetX: 20,
    bodyOffsetY: 20,
    scoreValue: 12,
    speedModifier: 1,
  },
  {
    key: 'missing-reqs',
    label: 'Missing Requirements',
    assetKey: 'obstacle-missing-requirements',
    accent: 0x4da68b,
    cropX: 79,
    cropY: 329,
    cropWidth: 922,
    cropHeight: 383,
    weight: 1.15,
    width: 196,
    height: 108,
    bodyWidth: 168,
    bodyHeight: 72,
    bodyOffsetX: 14,
    bodyOffsetY: 24,
    scoreValue: 14,
    speedModifier: 0.96,
  },
  {
    key: 'uat-fail',
    label: 'UAT Fail',
    assetKey: 'obstacle-uat-fail',
    accent: 0x51ac52,
    cropX: 269,
    cropY: 119,
    cropWidth: 507,
    cropHeight: 823,
    weight: 0.95,
    width: 94,
    height: 232,
    bodyWidth: 54,
    bodyHeight: 198,
    bodyOffsetX: 20,
    bodyOffsetY: 20,
    scoreValue: 18,
    speedModifier: 1.05,
  },
  {
    key: 'client-changed-mind',
    label: 'Client Changed Mind',
    assetKey: 'obstacle-client-changed-mind',
    accent: 0xb4a26f,
    cropX: 79,
    cropY: 329,
    cropWidth: 890,
    cropHeight: 383,
    weight: 0.86,
    width: 196,
    height: 108,
    bodyWidth: 168,
    bodyHeight: 72,
    bodyOffsetX: 14,
    bodyOffsetY: 24,
    scoreValue: 16,
    speedModifier: 1.04,
  },
  {
    key: 'integration-error',
    label: 'Integration Error',
    assetKey: 'obstacle-integration-error',
    accent: 0x6991c6,
    cropX: 79,
    cropY: 329,
    cropWidth: 889,
    cropHeight: 383,
    weight: 0.82,
    width: 196,
    height: 108,
    bodyWidth: 168,
    bodyHeight: 72,
    bodyOffsetX: 14,
    bodyOffsetY: 24,
    scoreValue: 17,
    speedModifier: 1.08,
  },
  {
    key: 'budget-freeze',
    label: 'Budget Freeze',
    assetKey: 'obstacle-budget-freeze',
    accent: 0x6d6d6d,
    cropX: 79,
    cropY: 329,
    cropWidth: 889,
    cropHeight: 383,
    weight: 0.74,
    width: 196,
    height: 108,
    bodyWidth: 168,
    bodyHeight: 72,
    bodyOffsetX: 14,
    bodyOffsetY: 24,
    scoreValue: 20,
    speedModifier: 1.12,
  },
  {
    key: 'one-more-change',
    label: 'One More Small Change',
    assetKey: 'obstacle-one-more-small-change',
    accent: 0x78b97d,
    cropX: 227,
    cropY: 169,
    cropWidth: 597,
    cropHeight: 713,
    weight: 0.7,
    width: 144,
    height: 210,
    bodyWidth: 100,
    bodyHeight: 118,
    bodyOffsetX: 22,
    bodyOffsetY: 48,
    scoreValue: 19,
    speedModifier: 1.1,
  },
];
